<?php

include('includes/gsapitest.admin.inc');

function gsapitest_menu() {
  $items['admin/settings/gsapi/gsapi-test'] = array(
    'title' => t('GS API Tests'),
    'page callback' => 'gsapitest_test',
    'access callback' => TRUE,
    'access arguments' => array('administer gs api'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );

  return $items;
}



function gsapitest_test() {
  return drupal_get_form('gsapitest_grd_form') . drupal_get_form('gsapitest_grpc_form') . drupal_get_form('gsapitest_gpcfr_form') . drupal_get_form('gsapitest_gipc_form') . drupal_get_form('gsapitest_aip_form') . drupal_get_form('gsapitest_rip_form') . drupal_get_form('gsapitest_gsl_form');
}
